### ISSUE TITLE
TKLDev 15.0 for 15.0 Library Release Checklist

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#1039]
This issue documents things needed to be fixed/changed/updated for the 15.0 version of tkldev to be ready for building the 15.0 version of the turnkey library.

- [x] - Deck package needs cleaning up (@JedMeister)
- [x] - Deck has layer-related issues that *may* prevent building (https://github.com/turnkeylinux/tracker/issues/1044)
- [ ] - ~~Deck no longer supports `--get-level` which breaks iso builds that include a modified root.sandbox~~ (defered to 15.1)
- [x] - OverlayFS not automatically loaded on boot
- [x] - `tkldev-setup` does not work properly on first boot
  - [x] - `tkldev-setup` requires dirmngr
  - [x] - `tkldev-setup` expects .sig files, but we use .hash files now to verify files (https://github.com/turnkeylinux/tracker/issues/947)
  - [x] - common master branch does not build on stretch and `tkldev-setup` clones the master branch of common

**Comment by JedMeister** [comment]
Seeing as all the points (other than "Deck no longer supports --get-level which breaks iso builds that include a modified root.sandbox" - which has been deferred to v15.1) have been resolved, I'm now closing this.
