### ISSUE TITLE
Security update takes down MariaDB (drop in MySQL replacement) - affects all apps with MariaDB; inc LAMP, WordPress, etc

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1246]
Affected appliances:
--------------------------

- [x] asp-net-apache
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] b2evolution
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] bugzilla
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] cakephp
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] codeigniter
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] collabtive
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] concrete5
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] django
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] drupal7
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] drupal8
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] e107
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] elgg
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] espocrm
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] ezplatform
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] foodsoft
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] foswiki
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] gallery
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] ghost
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] gitlab
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] gitea
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] gnusocial
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] icescrum
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] jenkins
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] joomla3
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] lamp
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] laravel
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] lighttpd-php-fastcgi
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] limesurvey
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] magento
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] mambo
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] mantis
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] matomo
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] mediawiki
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] mibew
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] moodle
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] mysql
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] nextcloud
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] nginx-php-fastcgi
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] observium
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] omeka
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] orangehrm
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] oscommerce
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] otrs
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] owncloud
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] phpbb
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] phplist
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] prestashop
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] processmaker
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] punbb
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] rails
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] redmine
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] roundup
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] sahana-eden
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] silverstripe
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] simpleinvoices
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] simplemachines
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] sitracker
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] suitecrm
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] symfony
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] tomcat
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] tomcat-apache
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] tracks
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] typo3
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] ushahidi
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] vanilla
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] web2py
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] wordpress
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] xoops
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] yiiframework
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] youphptube
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] zencart
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] zoneminder
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish
- [x] zurmo
   - [x] ready to build
   - [x] iso built
   - [x] ready to publish

----

Rob just reported in the [forums](https://www.turnkeylinux.org/forum/support/mon-20181119-1946/automatic-security-updates-broke-tkl-wordpress-15) that his WordPress server has gone down, complaining of a "database error" when he tries to connect.

I have just confirmed that there was a [MariaDB security update](https://security-tracker.debian.org/tracker/DSA-4341-1) released by Debian a few hours ago.

@OnGle is looking into it now and assuming that he can reproduce the issue, he will start work on finding a workaround and document here ASAP.

**Comment by JedMeister** [comment]
Wordaround/fix - reinstall `default-mysql-server`:
```
apt update
apt install default-mysql-server
```
That should reinstall `mariadb-client-10.1` & `mariadb-server-10.1` - to be sure check:
```
apt policy mariadb-client-10.1 mariadb-server-10.1
```

**Comment by JedMeister** [comment]
All images rebuilt. See [blog post](https://www.turnkeylinux.org/blog/v15.1-updates-bugfix) for more info.
