### ISSUE TITLE
Confconsole - Improvements for Let's Encrypt integration

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1365]
This is something of a "meta issue" for improvements that we could/should make for the Confconsole Let's Encrypt integration for v16.0. I have tagged it as a bug. Namely:

Todo
----

 - [x] <s>Ship with config in place (rather than relying on it being copied in on first run).</s> Decided to leave this be as is.
 - [x] Backup config files (especially domains.txt) before clobbering them with Confconsole (so worst case scenario, users can manually get back their domains). - resolved by https://github.com/turnkeylinux/confconsole/commit/e5060521b3411a8092617aa42861bb3b4ceab2a5.
 - [x] <s>Ensure that the APIv2 endpoint is configured by default.</s> We get this for free with the newer version of Dehydrated.
 - [ ] Include (optional) email address (covered in #823). **Deferred until v16.1**.

Wishlist
--------

 - [ ] Consider moving the dehydrated-wrapper script to `/usr/bin` so that it's easier to launch directly. - moved to it's own issue: #1430.
 - [x] <s>Tidy up the current dehydrated-wrapper script to remove the duplication between the wrapper script and the hook script. That alone may even resolve #1360?</s> This is now redundant, as we have resolved the Let's Encrypt/add-water issues so there is no real duplication now.

**Comment by OnGle** [comment]
Re "Ship with config in place". Currently the agreed fix to this is to not fix but document current behaviour.

**Comment by JedMeister** [comment]
Ok, I'[m closing this meta issue now. Everything either has it's own issue or has been resolved.
